### ISSUE TITLE
Team Harvery Wiley Code Review

### ISSUE THREAD

**Issue by Shelly1005** [vkeroles/EEP153-SP23-Proj4#12]
Dear Team Harvey,

I've reviewed your work on Project 3, and you've done a great job integrating the code from Project 2. However, I noticed that one of the deliverables, specifically 1.6(A) Nutritional Challenges & Policy Goals, was not addressed in your current implementation.

To ensure your project is comprehensive, I recommend adding a section to your code that compares predicted nutrition to recommended nutrition. Please revise your code to include this analysis on nutritional challenges and policy goals, as it will greatly enhance the overall value of your project. Thank you for your attention to this matter.

**Comment by vkeroles** [comment]
Hello Shelly, 

Thank you for your suggestions. Upon the submission of project to edtsem, you will find our updated final code on github with a section included with our take on policy goals and arising nutritional challenges. You will also find that graphs are now more clear with more specific titles and axis labels. 

Thank you.
