### ISSUE TITLE
Team Luther Tweeten Code Review

### ISSUE THREAD

**Issue by hoshiaip** [vkeroles/EEP153-SP23-Proj4#13]
Hi Team Harvey Wiley, 

Your code overall is very clear and I don't see any serious issue. I just have two small suggestions regarding visualization:
1. It's better to give a graph a title that's relevant to the content of the specific graph instead of a generic one (e.g. '2019 Uganda Data')
2. In the graphs with all the nutrients, the line colors are repetitive. For example, fiber and vitamin b-6 are both green. It is better to assign different colors to each nutrient. 

Team Luther Tweeten

**Comment by vkeroles** [comment]
Hello Team Luther Tweeten, 

Thank you for your suggestions. 

With regards to the graphs, I have decided to exclude the nutrients we are not interested in our analysis and this solves the issue of repetitive colors.  With regards to question 1, I have updated all graphs with more detailed titles and axis labels. Please see the notebook Team_HWiley_code2 to see these updates. Upon the deadline, this will be the final code and will be labeled Team_HWiley_code_final. 

Thank you
